### ISSUE TITLE
Swift 4 - iOS 11 - Cascade transitions doesn't work

### ISSUE THREAD

**Issue by morgan-legal** [HeroTransitions/Hero#293] opened 2017-10-13 08:21 UTC
Hi,

I'm using Hero in my application and it was working perfectly until iOS 11, I only have one issue though, I'm applying a `cascade` modifier on the tableView to display the each cells with a delay. I case see the cascade when I build the app on iOS 9 and 10 but not on iOS 11.

Is that a known issue ? Or many something that i'm missing ?

Thanks !
Morgan

**Comment by taiphamtiki** [comment] 2017-10-27 10:28
this work for me : 
```
        self.tableView.heroModifiers = [.cascade(delta: 2.0, direction: .bottomToTop, delayMatchedViews: true)]

        var i  = 1.0
        for cell in (self.tableView.visibleCells) {
            
            cell.heroModifiers = [.duration(0.125 * i),.translate(CGPoint.init(x: 0, y: 120))]
            i += 1
        }

```

**Comment by morgan-legal** [comment] 2017-11-14 14:43
Hi @taiphamtiki,

Thank you for your reply. I'm basically doing the same thing but it does not work. Are you testing on iOS 11 ? Which device ?

Thanks,
Morgan

**Comment by leo1mml** [comment] 2018-01-19 05:39
cascade is working for me only when I leave the view controller. I'm setting the hero modifiers into cellForRowAt method of a collectionview... Any help?

**Comment by morgan-legal** [comment] 2018-01-23 16:08
I can confirm that the cascading effect does not work on a UITableView but it does on a UICollectionView. 
The only way to have that effect on tableView cells would be to apply a modifier on each one of them with a delayed ( delta * index ) translate.

**Comment by r-dent** [comment] 2018-03-18 08:12
I don´t understand why this is closed. I can reproduce the error with iOS 11 and a `UITableView`.
Or in other words: What is needed to reopen this :-)

**Comment by morgan-legal** [comment] 2018-03-18 22:13
@lkzhao can this issue be re-opened ?

**Comment by lkzhao** [comment] 2018-03-18 22:16
Yea, definitely. I will take a look this week.

**Comment by kkrawczynski** [comment] 2018-06-10 10:17
i know this is not an answer but try version 0.3.6 
I had weird rendering problems in v1.0.0 (and up) when i was linking cell view's with VC's view's so ive decided to stick with 0.3.6

**Comment by morgan-legal** [comment] 2018-06-18 09:10
Yes the issue comes from the 1.0.0 release. I'd rather not roll back to previous versions but find a fix for current one :)

**Comment by evyasafm** [comment] 2019-01-09 17:09
On `UICollectionView` `.cascade` doesn't work with `RxSwift` binder (work as expected only with dataSource function `_:_:sizeForItemAt`)

**Comment by KonsoltCorp** [comment] 2019-02-28 03:41
Has a fix for this been made yet?

**Comment by morgan-legal** [comment] 2019-02-28 08:31
Not that I'm aware of...

**Comment by RomuloVHSYS** [comment] 2019-06-17 20:42
I'm unable to use cascate too, but i think that is because the tableView cell are not loaded on the moment that the transition animation occurs, and maybe that moment have changed on iOS 11+

**Comment by ilkerc** [comment] 2019-11-02 23:27
Try accessing `visibleCells`on `viewDidLayoutSubviews`

**Comment by JStrawn** [comment] 2020-06-15 11:00
Strangely enough, I have set them in almost everywhere in the view lifecycle, but I can only get the cascade animation to work when leaving the view. It seems like the animations are running in viewWillDisappear, but I can't get them to run after populating the datasource and reloading the collectionview.

**Closed** 2022-05-06 05:21 UTC
Labels: reopen if needed
