### ISSUE TITLE
Screen freezes if fast make push<->pop

### ISSUE THREAD

**Issue by EgorkZe** [HeroTransitions/Hero#599] opened 2019-04-12 08:32 UTC
HI! I found the issue when I make push<->pop transition. I tried to insert block with pop call to main.async closure but it did not help. Maybe someone have already found solution and can share with me?

**Comment by Maxim-Zakopaylov** [comment] 2019-04-18 13:17
Are you duplicated this issue https://github.com/HeroTransitions/Hero/issues/572 ?

**Comment by jensonjohn001** [comment] 2019-04-27 07:19
same problem..

**Comment by kuyazee** [comment] 2019-10-31 01:36
Closing issue since this is a duplicate of #572

**Closed by kuyazee** 2019-10-31 01:36 UTC
