### ISSUE TITLE
UIViewAnimationState memory leak (retaining self)

### ISSUE THREAD

**Issue by tifroz** [HeroTransitions/Hero#432] opened 2018-03-23 17:45 UTC
I found some issues running the Memory Graph Analyzer after going through a couple of Hero transitions. It looks like the UIViewAnimationState is retaining itself via the `animations` closure in _HeroCoreAnimationViewContext line 207_

```
UIView.animate(withDuration: duration, delay: delay, options: [], animations: animations, completion: nil)
```

<img width="1437" alt="screen shot 2018-03-23 at 10 37 24 am" src="https://user-images.githubusercontent.com/150367/37844995-968d4426-2e86-11e8-8dfb-d247657a9142.png">

**Comment by NeverwinterMoon** [comment] 2018-05-07 06:55
I also got the same when using non-modal animations (no such problem with modal).

I have a navigation controller and two view controllers. One segues to the other one (using push). I have Hero enabled on the navigation controller. Every transition from controller 1 to controller 2, I get 2 `UIViewAnimationState` -> `UIViewAnimationBlockDelegate` leaks.

Here is the key part: this only happens if I use `heroID` on 2 different views, one in each of the controllers. If I don't use that, but only the full-screen animation (I use `.fade`), there are no leaks reported by `Memory Graph Debug`.

**Comment by NeverwinterMoon** [comment] 2018-05-07 11:01
Here is the minimum required code to reproduce the problem: https://github.com/NeverwinterMoon/hero-retained-self

**Comment by hanawat** [comment] 2018-05-20 10:16
Any resolution of the issue?

**Comment by yorkwang** [comment] 2018-06-01 04:18
My app has the memory issue too when using modal animations.

**Comment by bitwit** [comment] 2018-07-05 15:08
Did a little more investigation into this:

1. Using `[weak self]` everywhere possible does not fix the problem
2. From my testing and analysis it seems that changing the frame in `setSize` causes the leak. If you comment out any lines that change the bounds or center the leaks disappear. very odd. Pasting the code from set size with offending lines commented out:

```swift
  func setSize(view: UIView, newSize: CGSize) {
    let oldSize = view.bounds.size
    if targetState.snapshotType != .noSnapshot {
      if oldSize.width == 0 || oldSize.height == 0 || newSize.width == 0 || newSize.height == 0 {
        for subview in view.subviews {
//          subview.center = newSize.center
//          subview.bounds.size = newSize
          setSize(view: subview, newSize: newSize)
        }
      } else {
        let sizeRatio = oldSize / newSize
        for subview in view.subviews {
          let center = subview.center
          let size = subview.bounds.size
//          subview.center = center / sizeRatio
//          subview.bounds.size = size / sizeRatio
          setSize(view: subview, newSize: size / sizeRatio)
        }
      }
//      view.bounds.size = newSize
    } else {
      view.bounds.size = newSize
      view.layoutSubviews()
    }
  }
```
The animations i tested with always went through the `  if targetState.snapshotType != .noSnapshot ` condition

I don't know a heck of a lot about this framework, but wondering if these animations should actually be happening via CGAffineTransform

**Comment by bitwit** [comment] 2018-07-05 15:24
Hmm, i just tried setting a random transform instead and it brought the leak back 😥

**Comment by bitwit** [comment] 2018-07-05 20:30
I think I've figured it out!

Forget the previous code shared above. While it was certainly triggering the issue, it wasn't the right place to be making changes.

It appears the solution is to wrap the UIView.animate on line 207 in a `DispatchQueue.main.async` and the problem goes away.

My lines 205 onward looked like this and the leak went away:
```swift
     } else {
      CATransaction.begin()
      CATransaction.setAnimationTimingFunction(timingFunction)
     
      let addedAnimations = CALayer.heroAddedAnimations!
      CALayer.heroAddedAnimations = nil
      for (layer, key, anim) in addedAnimations {
        layer.removeAnimation(forKey: key)
        addAnimation(anim, for: key, to: layer)
      }
      CATransaction.commit()
        
      DispatchQueue.main.async {
          CATransaction.begin()
          CATransaction.setAnimationTimingFunction(self.timingFunction)
          UIView.animate(withDuration: duration, delay: delay, options: [], animations: animations, completion: nil)
          CATransaction.commit()
      }
    }
```

Repeating the CATransaction code is necessary to set up the timing function for the UIView.animate otherwise it will be slightly out of sync. Once I have a firmer grasp of this lib I will make a pull request with the fix. It probably needs repeating for the spring damping block as well.

**Comment by bitwit** [comment] 2018-07-05 20:55
After getting ready to prepare a fix, it appears the latest code (no new version yet) already fixes this issue as of this commit: https://github.com/HeroTransitions/Hero/commit/f4dab9ed2ab88ae065605199d5aca7706b07c2ad

its frustratingly puzzling to me why this line of code made the difference but i stepped commit by commit from `1.2.0` and this one made the leak go away 🤷‍♂️ 

@lkzhao maybe you want to confirm this, but you might be able to close this ticket and the related one

**Comment by yorkwang** [comment] 2018-07-06 02:48
@bitwit Thank you very much!
 I have tested version 1.0.1, it doesn't have this leak issue.

**Comment by SD10** [comment] 2018-07-06 16:50
Hey @bitwit, thanks for all the awesome insight into this 💯 

I'm going to close this for now as it seems to be resolved as of Hero version 1.2.0. 

@tifroz @NeverwinterMoon Please try the latest version and feel free to re-open if you still experience this issue.

**Closed by SD10** 2018-07-06 16:50 UTC

**Comment by NeverwinterMoon** [comment] 2018-08-11 11:54
Sorry for a late reply. Did I understand correctly that it's still not in the latest version (1.3.0)? No need to test it out yet? @SD10

**Comment by NeverwinterMoon** [comment] 2018-08-11 12:08
OK, I just updated and checked. The problem that I was experiencing is certainly gone. This can be observed with the simple implementation that I used to reproduce my original problem here: https://github.com/NeverwinterMoon/hero-retained-self. Updated the project to use Hero 1.3.0 and the leak can't be observed any longer.
