### ISSUE TITLE
leaks   -   uiViewBasedAnimate

### ISSUE THREAD

**Issue by GordonLY** [HeroTransitions/Hero#449] opened 2018-04-23 10:37 UTC
![image](https://user-images.githubusercontent.com/16334572/39121866-8c555c16-4725-11e8-81ec-451289a4a6ae.png)
![image](https://user-images.githubusercontent.com/16334572/39121498-69237b16-4724-11e8-882d-4c30f0397b56.png)

i used hero when a tableviewCell click to push a new controller,
cell's image is the same heroId with the new controller's subview's image 
what i do is : 
![image](https://user-images.githubusercontent.com/16334572/39121742-1cccb7e0-4725-11e8-83c7-24469487c991.png)
the new controller just imageview.image.hero.id = "rrArticle_cover"

am I wrong?
what should I do？

**Comment by NeverwinterMoon** [comment] 2018-05-07 11:04
Seems to be a duplicate of this: https://github.com/lkzhao/Hero/issues/432

**Comment by Sepho** [comment] 2018-05-18 07:13
Same issue here. I've a tableView with a basic cell (text + image) and animates push transition using hero.id on cell's image and on a destination VC subview. If I look at memory usage it seems to work perfect, as it raises on push but it releases on pop so it remains stable but leaks instruments show a red icon on leaks row (leak appears when destination VC appears, not when I go back to previous VC).

**Comment by bitwit** [comment] 2018-07-05 20:30
Just posted a possible solution in: https://github.com/HeroTransitions/Hero/issues/432

**Comment by SD10** [comment] 2018-07-06 16:59
Going to close this one in favor of #432 (also closed). But feel free to move any discussion there

**Closed by SD10** 2018-07-06 16:59 UTC
Labels: bug
